// <auto-generated />
using System;
using EFormBuilder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFormBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320201209_InitialSnakeCase")]
    partial class InitialSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_answers_field_id");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("ix_answers_response_id");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_type");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.HasKey("Id")
                        .HasName("pk_fields");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_fields_form_id");

                    b.ToTable("fields", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.FieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_field_options");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_field_options_field_id");

                    b.ToTable("field_options", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_forms_user_id");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<string>("ResponderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("responder_email");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_responses");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_responses_form_id");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Answer", b =>
                {
                    b.HasOne("EFormBuilder.Domain.Entities.Field", "Field")
                        .WithMany("Answers")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_fields_field_id");

                    b.HasOne("EFormBuilder.Domain.Entities.Response", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_responses_response_id");

                    b.Navigation("Field");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Field", b =>
                {
                    b.HasOne("EFormBuilder.Domain.Entities.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fields_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.FieldOption", b =>
                {
                    b.HasOne("EFormBuilder.Domain.Entities.Field", "Field")
                        .WithMany("FieldOptions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_options_fields_field_id");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Form", b =>
                {
                    b.HasOne("EFormBuilder.Domain.Entities.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forms_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Response", b =>
                {
                    b.HasOne("EFormBuilder.Domain.Entities.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_responses_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Field", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("FieldOptions");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Form", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.Response", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("EFormBuilder.Domain.Entities.User", b =>
                {
                    b.Navigation("Forms");
                });
#pragma warning restore 612, 618
        }
    }
}
